NAME: 'efficientnet_series'

DIRS:
  TRAIN_IMAGES: "/media/datnt/data/medical-image-data/brain-mri-numpies/"
  VALIDATION_IMAGES: "/media/datnt/data/medical-image-data/brain-mri-numpies/"

DATA:
  NUMPIES: True
  TYPE: "multilabel"
  CSV:
    TRAIN: "csv/brain-mri-abnormalness-train-study.csv"
    VALIDATION: "csv/brain-mri-abnormalness-valid-study.csv"  
  INP_CHANNEL: 1

MODEL:
  NAME: "tf_efficientnet_b0"
  CLS_HEAD: "linear"
  NUM_CLASSES: 1
  DROPOUT: 0.5
  DROPPATH: 0.2

LOSS:
  NAME: "ce"

SOLVER:
  BASE_LR: 1e-4
  WARMUP_LENGTH: 1
  GD_STEPS: 1
  SWA:
    START_EPOCH: 2
    DECAY: 0.9
    FREQ: 1
    ENABLED: True
  
TRAIN:
  BATCH_SIZE: 32
  EPOCHES: [10]
